### ISSUE TITLE
Context should become Position

### ISSUE THREAD

**Issue by agorzawski** [tensorics/tensorics-core#13]
The current implementation uses Context (e.g. tensor.context()) that is a wrapper for an ordinary Position. 
It was justified as at some moment one would like to put more into the context. Nowadays we see that a Position is enough. Should be removed.

**NOTE** be careful on this change as it will break the tensor API...

**Comment by kaifox** [comment]
refactoring step in place, please have a look:
#17

**Comment by kaifox** [comment]
Final refactoring step in place. Please have a look.
#23

**Comment by kaifox** [comment]
Merged according branch into master and released (v0.0.40)
