### ISSUE TITLE
Dimension should not be limited to lowermost classes

### ISSUE THREAD

**Issue by kaifox** [tensorics/tensorics-core#3]
Instead, it should be possible to e.g. use an interface as a dimension.

**Comment by agorzawski** [comment]
Please check the test defined in the **CoordinatesOnInterfacesTest.class.** It is Simplified (only Double Tensor one) but covering the main issues we have. I will start investigating/coding slowly, fell free to change the test on  **interface-in-dimension branch**.

**Comment by michi42** [comment]
fixed by #8
