### ISSUE TITLE
Fix Travis build

### ISSUE THREAD

**Issue by kaifox** [tensorics/tensorics-core#43]
It seems that there is no travis build running anymore 

... could have to do with the fact that we should move to travis-ci.com instead of org...

**Comment by michi42** [comment]
I see a build at https://travis-ci.org/github/tensorics/tensorics-core :-)

However, moving to travis-ci.com would probably still be a good idea.

**Comment by kaifox** [comment]
Seems we noticed this some time ago, but forgot ;-) Thanks @michi42  and @andreacalia  for fixing it!
